export type Product = {
  repo_name: string;
  repo_full_name: string;
  repo_html_url: string;
  repo_doc: string;
  repo_usage: string;
  extension_id: string;
  icon_url: string;
  name: string;
  rating: number;
  review_count: number;
  thumbnail: string;
  description: string;
  category: string;
  users: number;
  promotion_image: string;
  screenshot_url: string;
  overview: string;
  developer: string;
  version: string;
  size: string;
  languages: string[];
  store_url: string;
  created_at: string;
  updated_at: string;
  provider: string;
  tags: string[];
};
