export type Product = {
  title: string;
  version: string;
  category: string;
  releaseDate: string;
  updateDate: string;
  rate: number;
  users: number;
  status: string;
  url: string;
  src: string;
  description: string;
  tags: string[];
  github: string;
  author: string;
  doc: string;
  usage: string;
  language: string;
  price: string;
  id: string;
  name: string;
  type: "dev" | "user" | "all" | "";
};
